create extension if not exists pgcrypto;

create table profiles(id uuid primary key references auth.users on delete cascade,nickname text,height_cm numeric,current_weight_kg numeric,goal_weight_kg numeric,goal_type text check(goal_type in('fat_loss','body_recomposition','maintain')),companion_name text not null default 'Momo',companion_style text not null default 'gentle',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table meal_logs(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users on delete cascade,meal_type text not null,eaten_at timestamptz not null default now(),input_type text not null,image_url text,raw_text text,estimated_calories numeric not null default 0,protein_g numeric not null default 0,carbs_g numeric not null default 0,fat_g numeric not null default 0,satiety_score smallint check(satiety_score between 1 and 10),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table food_items(id uuid primary key default gen_random_uuid(),meal_log_id uuid not null references meal_logs on delete cascade,name text not null,estimated_amount text,estimated_calories numeric,protein_g numeric,carbs_g numeric,fat_g numeric,confidence numeric check(confidence between 0 and 1),created_at timestamptz not null default now());
create table weight_logs(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users on delete cascade,logged_on date not null default current_date,weight_kg numeric not null check(weight_kg>0),created_at timestamptz not null default now(),unique(user_id,logged_on));
create table craving_sessions(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users on delete cascade,started_at timestamptz not null default now(),ended_at timestamptz,trigger_type text,emotion text,user_text text,initial_urge smallint check(initial_urge between 1 and 10),release_used boolean not null default false,final_urge smallint check(final_urge between 1 and 10),final_choice text,linked_meal_log_id uuid references meal_logs on delete set null);
create table memories(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users on delete cascade,memory_type text not null,content text not null,confidence numeric not null check(confidence between 0 and 1),created_at timestamptz not null default now(),last_confirmed_at timestamptz not null default now(),is_active boolean not null default true);
create table notification_preferences(user_id uuid primary key references auth.users on delete cascade,morning boolean not null default false,meal boolean not null default false,eating_window boolean not null default false,fasting_start boolean not null default false,daily_reflection boolean not null default false,updated_at timestamptz not null default now());
create index meal_logs_user_eaten_idx on meal_logs(user_id,eaten_at desc);create index craving_user_started_idx on craving_sessions(user_id,started_at desc);create index memory_user_active_idx on memories(user_id,is_active,memory_type);

alter table profiles enable row level security;alter table meal_logs enable row level security;alter table food_items enable row level security;alter table weight_logs enable row level security;alter table craving_sessions enable row level security;alter table memories enable row level security;alter table notification_preferences enable row level security;
create policy "own profiles" on profiles for all using(auth.uid()=id) with check(auth.uid()=id);create policy "own meals" on meal_logs for all using(auth.uid()=user_id) with check(auth.uid()=user_id);create policy "own food items" on food_items for all using(exists(select 1 from meal_logs m where m.id=meal_log_id and m.user_id=auth.uid())) with check(exists(select 1 from meal_logs m where m.id=meal_log_id and m.user_id=auth.uid()));create policy "own weights" on weight_logs for all using(auth.uid()=user_id) with check(auth.uid()=user_id);create policy "own cravings" on craving_sessions for all using(auth.uid()=user_id) with check(auth.uid()=user_id);create policy "own memories" on memories for all using(auth.uid()=user_id) with check(auth.uid()=user_id);create policy "own notification preferences" on notification_preferences for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
