create table chat_threads(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users on delete cascade,title text,summary text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table chat_messages(id uuid primary key default gen_random_uuid(),thread_id uuid not null references chat_threads on delete cascade,user_id uuid not null references auth.users on delete cascade,role text not null check(role in('user','assistant','system')),content jsonb not null,created_at timestamptz not null default now());
create table fasting_sessions(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users on delete cascade,started_at timestamptz not null,planned_end_at timestamptz not null,ended_at timestamptz,protocol text not null default '16:8',created_at timestamptz not null default now());
create table daily_reflections(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users on delete cascade,reflected_on date not null default current_date,mood smallint check(mood between 1 and 5),content text,ai_summary text,created_at timestamptz not null default now(),unique(user_id,reflected_on));
create table analytics_events(id uuid primary key default gen_random_uuid(),user_id uuid references auth.users on delete set null,event_name text not null,properties jsonb not null default '{}',created_at timestamptz not null default now());
create index chat_threads_user_idx on chat_threads(user_id,updated_at desc);create index chat_messages_thread_idx on chat_messages(thread_id,created_at);create index fasting_user_idx on fasting_sessions(user_id,started_at desc);create index analytics_name_created_idx on analytics_events(event_name,created_at desc);

alter table chat_threads enable row level security;alter table chat_messages enable row level security;alter table fasting_sessions enable row level security;alter table daily_reflections enable row level security;alter table analytics_events enable row level security;
create policy "own chat threads" on chat_threads for all using(auth.uid()=user_id) with check(auth.uid()=user_id);create policy "own chat messages" on chat_messages for all using(auth.uid()=user_id) with check(auth.uid()=user_id);create policy "own fasting sessions" on fasting_sessions for all using(auth.uid()=user_id) with check(auth.uid()=user_id);create policy "own reflections" on daily_reflections for all using(auth.uid()=user_id) with check(auth.uid()=user_id);create policy "own analytics" on analytics_events for all using(auth.uid()=user_id) with check(auth.uid()=user_id);

create or replace function public.create_profile_for_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.profiles(id,nickname) values(new.id,coalesce(new.raw_user_meta_data->>'nickname','新朋友')) on conflict(id) do nothing;return new;end;$$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.create_profile_for_new_user();
